### ISSUE TITLE
Assets - investigate bootstrap sprockets js loading

### ISSUE THREAD

**Issue by Nuanda** [Nuanda/smogmapper#15]
The bootstrap-sass gem is (probably) compiling all BS js code into our app.js. This is rather an overkill - shaving that a bit might save our mobile first-time users some time.

Find an elegant way to do that.

**Comment by mkasztelnik** [comment]
We currently including [`bootstrap-sprocket`](https://github.com/Nuanda/smogmapper/blob/master/app/assets/javascripts/application.js.coffee#L5) which is simply list of further includes (see https://github.com/twbs/bootstrap-sass/blob/master/assets/javascripts/bootstrap-sprockets.js). To minimize compiled boostrap JS concrete part of the bootstrap JS can be included (only these one which are used) instead of `bootstrap-sprocket`. Right now most probably: `bootstrap/button` and `bootstrap/tooltip`
