### ISSUE TITLE
Sensors are dissapearing

### ISSUE THREAD

**Issue by mkasztelnik** [Nuanda/smogmapper#41]
Try to zoom in/out couple of times. As a result sensors will (all or partially) disappear. This bug exists in current production deployment and also in master - no error in JS console.

**Comment by Nuanda** [comment]
Can't reproduce on my devices.

Can you test it with fewer (e.g. 30) sensors/markers? Does the problem show then?

Also, can you hook into zoom events and print out the number of markerLayer group getLayers() elements? If this stays constant then it might be some kind of leaflet's internal issue :(.

**Comment by Nuanda** [comment]
I think I was able to reproduce that on IE Edge Win 10. In my case it looks like only the "inner" set of markers are shown - as if leaflet thinks the boundaries of the visible map are much narrower than they really are (esp. the north boundary, in my case). It happens after a lot of zooming in/out. What is strange, after playing a bit more with the map, the issue is "fixed" and again all markers are visible.
